require 'rake'
require 'rake/testtask'
require 'rcov/rcovtask'
require 'rake/clean'

CLEAN.include('coverage')

task :default => [:test_units, :rcov]

Rake::TestTask.new('test_units') do |t|
  t.libs << ['src', 'test']
  t.pattern = 'test/test_*.rb'
  t.verbose = true
  t.warning = true
end

Rcov::RcovTask.new("rcov") do |test|
  test.libs << ['src', 'test']
  test.pattern = 'test/test_*.rb'
  test.verbose = true
  test.rcov_opts << '--exclude "spec/*,gems/*" '
  test.rcov_opts << '--no-rcovrt'
end
